package com.fendou.pojo;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.aname
     *
     * @mbg.generated
     */
    private String aname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.apwd
     *
     * @mbg.generated
     */
    private String apwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.id
     *
     * @return the value of t_admin.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.id
     *
     * @param id the value for t_admin.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.aname
     *
     * @return the value of t_admin.aname
     *
     * @mbg.generated
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.aname
     *
     * @param aname the value for t_admin.aname
     *
     * @mbg.generated
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.apwd
     *
     * @return the value of t_admin.apwd
     *
     * @mbg.generated
     */
    public String getApwd() {
        return apwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.apwd
     *
     * @param apwd the value for t_admin.apwd
     *
     * @mbg.generated
     */
    public void setApwd(String apwd) {
        this.apwd = apwd == null ? null : apwd.trim();
    }
}